### ISSUE TITLE
Configuration Editor

### ISSUE THREAD

**Issue by daeks** [daeks/RetroPie-WebGui#6]
- [x] /etc/emulationstation/es_systems.cfg
- [x] /opt/retropie/configs/all/retroarch.cfg
- [x] /opt/retropie/configs/all/autostart.sh
- [x] /home/pi/.emulationstation/es_input.cfg
- [x] /home/pi/.emulationstation/es_settings.cfg
- [x] retroarch-joypads
- [x] Emulator's emulators.cfg and retroarch.cfg

**Comment by grenade44** [comment]
I have different configs for different consoles. Would love to be able to edit these as well some day.

**Comment by daeks** [comment]
you mean emulators.cfg and retroarch.cfg from the specific emulator folders?

**Comment by grenade44** [comment]
Yes

**Comment by daeks** [comment]
Does it go in the right direction?

![image](https://cloud.githubusercontent.com/assets/3989440/23395802/d5ff5ce8-fd90-11e6-8ac3-afefa7785679.png)

![image](https://cloud.githubusercontent.com/assets/3989440/23395787/bb85c3e8-fd90-11e6-87dc-e05f97f1e983.png)

**Comment by grenade44** [comment]
This looks great, I will update and test it later today.

**Comment by grenade44** [comment]
Just tested this and changed my emulator default and went to start a game and my default had successfully changed. I changed it back and then it decided to reset my retroarch config for that core. Not sure if that's due to ur app or retropie having a funny moment. Will test more later.
